# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d570acc3b1d992b35cfea5e746a8b0ac9e4f798fb634e938bece8371299ae056e894497c57ea761cf43ee2d00a8f8698279c55411d49dde7381874c232c8e3dc

test:
  secret_key_base: ed31526b3f3944b1a33b16991774928550fb406b2f2d0ee24f48e534f18be1388eb447b2ce3c7aae29cafd7e0f4a8c163a7ec39c79c6b226ae2fb812481102eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
